Add Telegram and Slack attrubutes
AY2223S1-CS2103T-W08-2/tp pull request #56
Opened 2022-10-11 10:09 UTC by arnav-ag

2022-10-11 12:17 UTC, Tex-Tang commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +            + PREFIX_TELEGRAM + "311, Clementi Ave 2, #02-25 "
`311, Clementi Ave 2, #02-25 ` is not an address, should we change it to telegram handle instead.

2022-10-11 12:17 UTC, Tex-Tang commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +        private Slack slack;
As we discussed before, we should use a hashMap to store this contact information such as `HashMap<ContactEnum, Contact>`

2022-10-11 12:19 UTC, Tex-Tang commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +            return Optional.ofNullable(slack);
```
public void setContact(ContactEnum, Contact)
public Optional<Contact> getContact
```

These might make `Person` class more extensible in terms of managing contact.

2022-10-11 12:21 UTC, Tex-Tang commented on src/main/java/seedu/address/logic/parser/AddCommandParser.java
>          }
Do we still need this guard as our command line usage is `add <name>`?

2022-10-11 12:22 UTC, Tex-Tang commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +        String trimmedTelegram= telegram.trim();
I think you missed a space here.

2022-10-11 12:23 UTC, Tex-Tang commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +        if (!Telegram.isValidTelegram(trimmedSlack)) {
Here should be validating slack account.

2022-10-11 12:25 UTC, Tex-Tang commented on src/main/java/seedu/address/model/person/Person.java
> +        return this;
As we discussed before, we should use a hashMap to store this contact information such as `HashMap<ContactEnum, Contact>`

2022-10-11 12:25 UTC, Tex-Tang commented on src/main/java/seedu/address/model/person/contact/Slack.java
> +        super(CONTACT_TYPE);
We can make use of `CONTACT_TYPE` in our contact hashmap.

2022-10-11 19:08 UTC, sh4nH approved these changes
LGTM

2022-10-12 11:15 UTC, Tex-Tang requested changes

2022-10-12 11:15 UTC, Tex-Tang commented on src/main/java/seedu/address/model/person/contact/Phone.java
>      }
We can put these Logic to `Contact` class so we don't need to repeat every time.

2022-10-12 11:15 UTC, Tex-Tang commented on src/main/java/seedu/address/model/person/contact/Slack.java
> +    }
We can put these Logic to `Contact` class so we don't need to repeat every time.

2022-10-12 11:15 UTC, Tex-Tang commented on src/main/java/seedu/address/model/person/contact/Slack.java
> +    }
Abstract `Contact` class already had this logic.

2022-10-12 11:15 UTC, Tex-Tang commented on src/main/java/seedu/address/model/person/contact/Telegram.java
> +}
We can put these Logic to `Contact` class so we don't need to repeat every time.

2022-10-12 11:15 UTC, Tex-Tang commented on src/main/java/seedu/address/model/tag/Tag.java
>  public class Tag {
I think `Tag` should change to `Role` instead.

2022-10-12 11:15 UTC, Tex-Tang commented on src/main/java/seedu/address/ui/PersonListPanel.java
> +        EventHandler<KeyEvent> keyEventHandler = new EventHandler<>() {
Thanks for correcting this error.

2022-10-12 11:15 UTC, Tex-Tang commented on src/main/java/seedu/address/ui/ContactBox.java
> +                }
We should show an error `AlertBox` here instead.
```java
Alert a = new Alert(Alert.AlertType.ERROR);
contactLabel.setOnAction(e -> {
    if (Desktop.isDesktopSupported()) {
        try {
            Desktop.getDesktop().browse(new URI(contact.getLink()));
        } catch (IOException ex) {
            a.setContentText("Sorry, browser couldn't be opened.");
            a.show();
        } catch (URISyntaxException ex) {
            a.setContentText("Sorry, url is invalid");
            a.show();
        }
    }
});
```

2022-10-12 11:15 UTC, Tex-Tang commented on src/main/java/seedu/address/ui/PersonCard.java
> +        // person.getTag().ifPresent(tag -> this.tag.setText(tag.tagName));
Any reason for this comment?

2022-10-13 13:08 UTC, closed without merging