Remove phone and email attributes
AY2223S1-CS2103T-W08-2/tp pull request #80
Opened 2022-10-13 12:24 UTC by arnav-ag

2022-10-13 13:05 UTC, Tex-Tang requested changes

2022-10-13 13:05 UTC, Tex-Tang commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +
Remove this extra line.

2022-10-13 13:13 UTC, Tex-Tang approved these changes
LGTM

2022-10-14 11:59 UTC, wrewsama approved these changes
lgtm

2022-10-14 12:18 UTC, merged